settings:
  name: Cloud Volumes ONTAP 9.5 release notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  versions:
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-95-relnotes
      version-number: "9.5"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-relnotes
      version-number: "9.14.0"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-9131-relnotes
      version-number: "9.13.1"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-9130-relnotes
      version-number: "9.13.0"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-9121-relnotes
      version-number: "9.12.1"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-9120-relnotes
      version-number: "9.12.0"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-9111-relnotes
      version-number: "9.11.1"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-9110-relnotes
      version-number: "9.11.0"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-9101-relnotes
      version-number: "9.10.1"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-9100-relnotes
      version-number: "9.10.0"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-991-relnotes
      version-number: "9.9.1"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-990-relnotes
      version-number: "9.9.0"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-98-relnotes
      version-number: "9.8"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-97-relnotes
      version-number: "9.7"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-96-relnotes
      version-number: "9.6"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-94-relnotes
      version-number: "9.4"
    - name: ONTAP Cloud
      url: /cloud-volumes-ontap-93-relnotes
      version-number: "9.3"
sidebar:
  entries:
    - title: Release notes home
      url: /index.html
    - title: What's new
      url: /reference-new.html
    - title: Supported configurations
      url: /reference-supported-configs.html
    - title: Storage limits
      url: /reference-storage-limits.html
    - title: Known issues
      url: /reference-issues.html
    - title: Known limitations
      url: /reference-limitations.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: All BlueXP documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: What's new
          url: reference-new.html
    - title: Configurations and limits
      links:
        - title: Supported configurations
          url: reference-supported-configs.html
        - title: Storage limits
          url: reference-storage-limits.html
        - title: Limitations
          url: reference-limitations.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
